### PR TITLE
Interactivetimeline

### PR DESCRIPTION
**Pull request by dxt121730**
Generic stories button in header remains unchanged, still points to `Stories` container.

### CODE REVIEW

**Comment by dxt121730** [comment]
Not sure why it's showing it as two commits in this PR, but it should just be that minor change to the `Dashboard` container

**Comment by ColeDeanShepherd** [comment]
We also need to separate the Apollo 11 Explorer code from the StoryTimeline component. I might do that in the next couple of days.

**Comment by ColeDeanShepherd** [comment]
I have concerns about the mixed use of "met_start" and "metStart" in the code/API. I'm not 100% sure if the code uses them correctly after my last commit, but I needed to get my progress in. Still working on it.

**Comment by ColeDeanShepherd** [comment]
I moved the old Apollo 11 moment viewer to components/Apollo11StoryTimeline

**Comment by ColeDeanShepherd** [comment]
I think that we just need to update the times in [https://github.com/UTD-CRSS/app.exploreapollo.org/blob/interactivetimeline/src/containers/Apollo11Explorer/index.js](https://github.com/UTD-CRSS/app.exploreapollo.org/blob/interactivetimeline/src/containers/Apollo11Explorer/index.js) now.

**Comment by austinpray** [comment]
Can you pull from the base branch? It looks out of date to me

**Comment by ColeDeanShepherd** [comment]
Yep, it's done.

**Pull request merged**
